export const FETCH_GOALS = 'FETCH_GOALS'
export const REQUEST_GOALS = 'REQUEST_GOALS'
export const REQUEST_GOALS_ERROR = 'REQUEST_GOALS_ERROR'
export const RECEIVE_GOALS = 'RECEIVE_GOALS'

export const CLEAR_STORAGE = 'CLEAR_STORAGE'
export const CLEAR_PROGRESS = 'CLEAR_PROGRESS'

export const ADD_GOAL = 'ADD_GOAL'
export const DELETE_GOAL = 'DELETE_GOAL'
export const EDIT_GOAL = 'EDIT_GOAL'
export const ACHIEVE_GOAL = 'ACIEVE_GOAL'
export const RESET_GOAL = 'RESET_GOAL'

export const RECEIVE_PROGRESS = 'RECEIVE_PROGRESS'
export const INCREMENT_PROGRESS = 'INCREMENT_PROGRESS'
export const DECREMENT_PROGRESS = 'DECREMENT_PROGRESS'
