export const ADD_GOAL = 'ADD_GOAL'
export const DELETE_GOAL = 'DELETE_GOAL'
export const EDIT_GOAL = 'EDIT_GOAL'
export const ACHIEVE_GOAL = 'ACIEVE_GOAL'
export const RESET_GOAL = 'RESET_GOAL'

export const INCREMENT_PROGRESS = 'INCREMENT_PROGRESS'
export const DECREMENT_PROGRESS = 'DECREMENT_PROGRESS'
